# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitle', models.TextField(blank=True, verbose_name='Entradilla')),
                ('text', models.TextField(blank=True, verbose_name='Descripción')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Empieza en')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Termina en')),
                ('duration', models.CharField(max_length=50, verbose_name='Duración aproximada')),
                ('max_places', models.IntegerField(default=0, verbose_name='Nº máximo de plazas')),
                ('logistics', models.TextField(blank=True, verbose_name='Necesidades logísticas')),
                ('notes_organization', models.TextField(blank=True, verbose_name='Comentarios')),
                ('has_view_page', models.BooleanField(default=False, verbose_name='Tiene página propia')),
                ('show_owners', models.BooleanField(default=False, verbose_name='Mostrar responsables')),
                ('requires_inscription', models.BooleanField(default=False, verbose_name='Requiere inscripción')),
                ('organizers', models.ManyToManyField(blank=True, related_name='organizer_of', to=settings.AUTH_USER_MODEL, verbose_name='Organizadores')),
                ('owners', models.ManyToManyField(related_name='owner_of', to=settings.AUTH_USER_MODEL, verbose_name='Responsables')),
                ('participants', models.ManyToManyField(blank=True, related_name='participant_of', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['start', 'end'],
            },
        ),
    ]
