# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='column',
            field=models.IntegerField(choices=[(0, 'Ancho completo'), (1, 'Columna 1'), (2, 'Columna 2')], default=0, verbose_name='Columna'),
        ),
    ]
