# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100, verbose_name='pseudónimo')),
                ('smial', models.CharField(blank=True, max_length=100, verbose_name='smial')),
                ('phone', models.CharField(max_length=100, verbose_name='teléfono')),
                ('city', models.CharField(max_length=100, verbose_name='población')),
                ('age', models.IntegerField(verbose_name='edad')),
                ('dinner_menu', models.CharField(blank=True, choices=[('carne', 'Carne'), ('pescado', 'Pescado'), ('otros', 'Otros'), ('sin-cena', 'No voy a ir a la cena de gala')], max_length=50, verbose_name='Menú de la cena de gala')),
                ('notes_food', models.TextField(blank=True, verbose_name='Comentarios comida')),
                ('day_1', models.BooleanField(default=True, verbose_name='Asistencia viernes/sábado')),
                ('day_2', models.BooleanField(default=True, verbose_name='Asistencia sábado/domingo')),
                ('day_3', models.BooleanField(default=True, verbose_name='Asistencia domingo/lunes+cena')),
                ('notes_transport', models.TextField(blank=True, verbose_name='Comentarios transporte')),
                ('room_choice', models.CharField(choices=[('Albergue (litera y baño comunitario)', (('albergue-completa', '(litera) completa'), ('albergue-v-a-d', '(litera) viernes a domingo'), ('albergue-s-y-d', '(litera) sábado y domingo'))), ('Habitación doble con baño propio', (('doble-completa', '(doble) completa'), ('doble-v-a-d', '(doble) viernes a domingo'), ('doble-s-y-d', '(doble) sábado y domingo'))), ('sin-alojamiento', 'No voy a pernoctar en el seminario'), ('otros', 'Otros')], max_length=50, verbose_name='Elige un tipo de alojamiento')),
                ('room_preferences', models.TextField(blank=True, verbose_name='¿Tienes alguna preferencia sobre con quién compartir habitación?')),
                ('children_count', models.IntegerField(default=0, verbose_name='¿Traes niños a tu cargo? Si es así, indica cuántos')),
                ('children_names', models.TextField(blank=True, verbose_name='Indica sus nombres, uno en cada línea')),
                ('is_ste_member', models.BooleanField(default=True, verbose_name='¿Eres socio/a de la STE?')),
                ('want_ste_member', models.BooleanField(default=False, verbose_name='En caso de que no, ¿quieres asociarte por 2€ más?')),
                ('squire', models.BooleanField(default=False, verbose_name='¿Quieres ser escudero?')),
                ('first_estelcon', models.BooleanField(default=False, verbose_name='¿Es tu primera Estelcon?')),
                ('want_boat', models.BooleanField(default=False, verbose_name='¿Quieres remontar en barco por el río?')),
                ('notes_general', models.TextField(blank=True, verbose_name='Comentarios general')),
                ('shirts_S', models.IntegerField(default=0, verbose_name='Camisetas talla S')),
                ('shirts_M', models.IntegerField(default=0, verbose_name='Camisetas talla M')),
                ('shirts_L', models.IntegerField(default=0, verbose_name='Camisetas talla L')),
                ('shirts_XL', models.IntegerField(default=0, verbose_name='Camisetas talla XL')),
                ('shirts_XXL', models.IntegerField(default=0, verbose_name='Camisetas talla XXL')),
                ('quota', models.IntegerField(verbose_name='Cuota')),
                ('payed', models.IntegerField(verbose_name='Pagado')),
                ('payment', models.TextField(verbose_name='Estado de pago')),
                ('lost', models.CharField(blank=True, max_length=50, verbose_name='(dato interno)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de usuario',
                'verbose_name_plural': 'Fichas de usuario',
                'ordering': ('id',),
            },
        ),
    ]
