# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='want_boat',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='want_bus',
            field=models.BooleanField(default=False, verbose_name='¿Vas a utilizar el autobús de Valencia?'),
        ),
    ]
