# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_auto_20180702_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shirts_L',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shirts_M',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shirts_S',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shirts_XL',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shirts_XXL',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirts_L_1',
            field=models.IntegerField(default=0, verbose_name='Camisetas talla L (1)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirts_L_2',
            field=models.IntegerField(default=0, verbose_name='Camisetas talla L (2)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirts_L_3',
            field=models.IntegerField(default=0, verbose_name='Camisetas talla L (3)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirts_M_1',
            field=models.IntegerField(default=0, verbose_name='Camisetas talla M (1)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirts_M_2',
            field=models.IntegerField(default=0, verbose_name='Camisetas talla M (2)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirts_M_3',
            field=models.IntegerField(default=0, verbose_name='Camisetas talla M (3)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirts_S_1',
            field=models.IntegerField(default=0, verbose_name='Camisetas talla S (1)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirts_S_2',
            field=models.IntegerField(default=0, verbose_name='Camisetas talla S (2)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirts_S_3',
            field=models.IntegerField(default=0, verbose_name='Camisetas talla S (3)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirts_XL_1',
            field=models.IntegerField(default=0, verbose_name='Camisetas talla XL (1)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirts_XL_2',
            field=models.IntegerField(default=0, verbose_name='Camisetas talla XL (2)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirts_XL_3',
            field=models.IntegerField(default=0, verbose_name='Camisetas talla XL (3)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirts_XXL_1',
            field=models.IntegerField(default=0, verbose_name='Camisetas talla XXL (1)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirts_XXL_2',
            field=models.IntegerField(default=0, verbose_name='Camisetas talla XXL (2)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirts_XXL_3',
            field=models.IntegerField(default=0, verbose_name='Camisetas talla XXL (3)'),
        ),
    ]
