# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_auto_20180702_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='want_bus',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='want_mentor',
            field=models.BooleanField(default=False, verbose_name='¿Querrías participar en el programa de mentorazgo a nuevos asistentes?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='room_choice',
            field=models.CharField(choices=[('Habitación individual', (('individual-completa', '(individual) completa'), ('individual-v-a-d', '(individual) viernes a domingo'), ('individual-s-y-d', '(individual) sábado y domingo'))), ('Habitación con suplemento', (('suplemento-completa', '(suplemento) completa'), ('suplemento-v-a-d', '(suplemento) viernes a domingo'), ('suplemento-s-y-d', '(suplemento) sábado y domingo'))), ('otros', 'Otros')], max_length=50, verbose_name='Elige un tipo de alojamiento'),
        ),
    ]
