# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_auto_20190122_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='want_media',
            field=models.BooleanField(default=False, verbose_name='Autorizo el uso de material audiovisual generado durante el evento Mereth Aderthad 2019 en donde se me pueda identificar por parte de la Sociedad Tolkien Española en su labor de difusión de actividades'),
        ),
    ]
