# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0005_userprofile_want_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='room_choice',
            field=models.CharField(choices=[('Habitación compartida', (('compartida-completa', '(compartida) completa'), ('compartida-v-a-d', '(compartida) viernes a domingo'), ('compartida-s-y-d', '(compartida) sábado y domingo'))), ('Habitación individual', (('individual-completa', '(individual) completa'), ('individual-v-a-d', '(individual) viernes a domingo'), ('individual-s-y-d', '(individual) sábado y domingo'))), ('otros', 'Otros')], max_length=50, verbose_name='Elige un tipo de alojamiento'),
        ),
    ]
