# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0006_auto_20190123_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='want_ste_member',
            field=models.BooleanField(default=False, verbose_name='En caso de que no, ¿quieres asociarte por 12€ más?'),
        ),
    ]
